### ISSUE TITLE
[crash] ClassCastException after installing

### ISSUE THREAD

**Issue by kawazoe** [linux-china/vitest-jetbrains-plugin#11]
After I installed the plugin (and did NOT restart WebStorm as I was not prompted to), I opened a test file to see if the plugin was loaded correctly. The `run` and `watch` icons took a second to show, then WebStorm reported the following stacktrace in its "IDE Internal Errors" window.

> WebStorm 2022.1.1
> Build #WS-221.5591.52, built on May 10, 20
> Runtime version: 11.0.14.1+1-b2043.45 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> OS: Garuda Linux

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class com.github.linuxchina.jetbrains.plugins.vitest.AssertionResult (java.lang.String is in module java.base of loader 'bootstrap'; com.github.linuxchina.jetbrains.plugins.vitest.AssertionResult is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5b8f57ac)
	at com.github.linuxchina.jetbrains.plugins.vitest.ui.VitestTreeCellRender.getTreeCellRendererComponent(VitestToolWindowFactory.kt:132)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:166)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:509)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.updateNodeSizes(VariableHeightLayoutCache.java:903)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.invalidateSizes(VariableHeightLayoutCache.java:371)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setCellRenderer(BasicTreeUI.java:465)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3816)
	at com.intellij.ui.tree.ui.DefaultTreeUI$5.propertyChange(DefaultTreeUI.java:616)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8756)
	at java.desktop/javax.swing.JTree.setCellRenderer(JTree.java:776)
	at com.github.linuxchina.jetbrains.plugins.vitest.ui.VitestToolWindowPanel.vitestTree(VitestToolWindowFactory.kt:85)
	at com.github.linuxchina.jetbrains.plugins.vitest.ui.VitestToolWindowPanel.<init>(VitestToolWindowFactory.kt:40)
	at com.github.linuxchina.jetbrains.plugins.vitest.ui.VitestToolWindowFactory.createToolWindowContent(VitestToolWindowFactory.kt:29)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:529)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:508)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:921)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:861)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:586)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:565)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1930)
	at com.intellij.toolWindow.StripeButton$1.actionPerformed(StripeButton.kt:59)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.toolWindow.StripeButton.processMouseEvent(StripeButton.kt:248)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by linux-china** [comment]
Could you try attachment version?  It's caused by Vitest toolWindow.

[vitest-jetbrains-plugin-0.4.1.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/8766344/vitest-jetbrains-plugin-0.4.1.zip)

**Comment by kawazoe** [comment]
> It's caused by Vitest toolWindow.

Indeed. It happens every time I try to open the tool window.

Same thing with this new version:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class com.github.linuxchina.jetbrains.plugins.vitest.AssertionResult (java.lang.String is in module java.base of loader 'bootstrap'; com.github.linuxchina.jetbrains.plugins.vitest.AssertionResult is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @23cea697)
	at com.github.linuxchina.jetbrains.plugins.vitest.ui.VitestTreeCellRender.getTreeCellRendererComponent(VitestToolWindowFactory.kt:132)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:166)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:509)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
```

Since the rest of the plugin works fine, would you prefer to ignore the problem and wait for the official support?

I've also discovered from the YouTrack thread that there is a `@vitest/ui` package that can be used with `vitest watch --ui`. That might be a simpler way to include a UI for you as a temporary measure.

**Comment by linux-china** [comment]
@kawazoe  it caused by test file without test methods.   I fixed it and release it to plugin marketplace.   Please try it again. 
[vitest-jetbrains-plugin-0.4.1.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/8766652/vitest-jetbrains-plugin-0.4.1.zip)

**Comment by kawazoe** [comment]
If you think this is caused by an empty test file then I know exactly what's going on. I didn't had a `.vitest-result.json` yet when I got the error initially. I had just installed the plugin and didn't went through the rest of the readme yet.

This new version seems to work fine even without the test result file, though I am getting a different error now.

After running the "webstorm-integration" script, the tool window didn't update, so I tried restart WebStorm to force it to load and got this parsing error:

```
java.security.PrivilegedActionException: java.security.PrivilegedActionException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "displayName" (class com.github.linuxchina.jetbrains.plugins.vitest.TestResult), not marked as ignorable (6 known properties: "status", "assertionResults", "message", "endTime", "name", "startTime"])
 at [Source: (File); line: 15, column: 23] (through reference chain: com.github.linuxchina.jetbrains.plugins.vitest.VitestTestResult["testResults"]->java.util.ArrayList[0]->com.github.linuxchina.jetbrains.plugins.vitest.TestResult["displayName"])
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.security.PrivilegedActionException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "displayName" (class com.github.linuxchina.jetbrains.plugins.vitest.TestResult), not marked as ignorable (6 known properties: "status", "assertionResults", "message", "endTime", "name", "startTime"])
 at [Source: (File); line: 15, column: 23] (through reference chain: com.github.linuxchina.jetbrains.plugins.vitest.VitestTestResult["testResults"]->java.util.ArrayList[0]->com.github.linuxchina.jetbrains.plugins.vitest.TestResult["displayName"])
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	... 20 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "displayName" (class com.github.linuxchina.jetbrains.plugins.vitest.TestResult), not marked as ignorable (6 known properties: "status", "assertionResults", "message", "endTime", "name", "startTime"])
 at [Source: (File); line: 15, column: 23] (through reference chain: com.github.linuxchina.jetbrains.plugins.vitest.VitestTestResult["testResults"]->java.util.ArrayList[0]->com.github.linuxchina.jetbrains.plugins.vitest.TestResult["displayName"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
	at com.github.linuxchina.jetbrains.plugins.vitest.VitestService.reloadVitestJsonResultFile(VitestService.kt:104)
	at com.github.linuxchina.jetbrains.plugins.vitest.VitestService.<init>(VitestService.kt:31)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.github.linuxchina.jetbrains.plugins.vitest.ui.VitestToolWindowPanel.vitestTree(VitestToolWindowFactory.kt:85)
	at com.github.linuxchina.jetbrains.plugins.vitest.ui.VitestToolWindowPanel.switchToScriptInfoPanel(VitestToolWindowFactory.kt:78)
	at com.github.linuxchina.jetbrains.plugins.vitest.ui.VitestToolWindowPanel.<init>(VitestToolWindowFactory.kt:47)
	at com.github.linuxchina.jetbrains.plugins.vitest.ui.VitestToolWindowFactory.createToolWindowContent(VitestToolWindowFactory.kt:29)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:529)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:508)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:921)
        ... 35 more
```

Here's what my json file look like (simplified):

```json
{
  "numTotalTestSuites": 7,
  "numPassedTestSuites": 7,
  "numFailedTestSuites": 0,
  "numPendingTestSuites": 0,
  "numTotalTests": 21,
  "numPassedTests": 21,
  "numFailedTests": 0,
  "numPendingTests": 0,
  "numTodoTests": 0,
  "startTime": 1653432548143,
  "success": true,
  "testResults": [
    {
      "displayName": "should be created in a neutral state",
      "skipped": false,
      "status": "pass",
      "testFilePath": "/home/..."
    },
    ...
  ]
}
```

For some reason, it looks like the tests results uses `displayName` instead of `name` like you expect. I am using the `describe`/`it` syntax, so maybe that's might produce results that are different from what you expected?

**Comment by linux-china** [comment]
@kawazoe  it's my fault and I forgot to add `FAIL_ON_UNKNOWN_PROPERTIES` feature for ObjectMapper to parse json file. 
Fixed with attached version.  Thanks for your feedback.  

[vitest-jetbrains-plugin-0.4.1.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/8766895/vitest-jetbrains-plugin-0.4.1.zip)

**Comment by kawazoe** [comment]
Looks fine now!

Thanks for the fix :)
